apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: modelversion.apicurio.io
spec:
  names:
    plural: modelversions
    singular: modelversion
    kind: ModelVersion
    shortNames:
      - mv
  scope: Namespaced
  group: apicurio.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                registryUrl:
                  type: string
                artifactName:
                  type: string
                artifactVersion:
                  type: string
                mode:
                  type: string
                  default: "LATEST"
                  enum:
                    - "LATEST"
                    - "FIXED"
              required:
                - registryUrl
                - artifactName
                - mode
            status:
              type: object
              properties:
                status:
                  type: string
                artifactVersion:
                  type: string
      subresources:
        status: {}