apiVersion: v1
stringData:
  registryMinio: |
    {
      "type": "s3",
      "access_key_id": "MINIO_ACCESS_KEY",
      "secret_access_key": "MINIO_SECRET_KEY",
      "endpoint_url": "http://registry-external-ref-minio.fly.dev:9000",
      "bucket": "models",
      "region": "us-east-1",
      "anonymous": "False",
      "secure": "False"
    }
kind: Secret
metadata:
  name: storage-config
  namespace: modelmesh-serving
type: Opaque
