# fly.toml app configuration file generated for registry-external-ref-minio on 2023-05-17T11:51:00+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "registry-external-ref-minio"
primary_region = "mad"

[[mounts]]
  source = "miniodata"
  destination = "/data"

# Letting public access to minio
[http_service]
  internal_port = 9001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0


[[services]]
  http_checks = []
  # use ipv6 to resolve the address or pay for a static ipv4
  internal_port = 9000
  protocol = "tcp"
  script_checks = []
[[services]]
  protocol = "tcp"
  internal_port = 9000
  [[services.ports]]
    port = 9000
