---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-05-24 - 17:02:35 +0000
    app.quarkus.io/commit-id: c5ccbf4787ad1ee66aed94754ccf98e6c2008a41
  labels:
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
    app.kubernetes.io/name: model-registry-sync-operator
    app.kubernetes.io/managed-by: quarkus
  name: model-registry-sync-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controller-cluster-role
rules:
  - apiGroups:
      - apicurio.io
      - serving.kserve.io
    resources:
      - modelversions
      - modelversions/status
      - modelversions/finalizers
      - inferenceservices
      - inferenceservices/status
      - inferenceservices/finalizers
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: josdk-crd-validating-cluster-role
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: controller-cluster-role-binding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: controller-cluster-role
subjects:
  - kind: ServiceAccount
    name: model-registry-sync-operator
    namespace: modelmesh-serving
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: controller-crd-validating-role-binding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: josdk-crd-validating-cluster-role
subjects:
  - kind: ServiceAccount
    name: model-registry-sync-operator
    namespace: modelmesh-serving
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: model-registry-sync-operator-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: model-registry-sync-operator
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-05-24 - 17:02:35 +0000
    app.quarkus.io/commit-id: c5ccbf4787ad1ee66aed94754ccf98e6c2008a41
  labels:
    app.kubernetes.io/name: model-registry-sync-operator
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: model-registry-sync-operator
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: model-registry-sync-operator
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-05-24 - 17:02:35 +0000
    app.quarkus.io/commit-id: c5ccbf4787ad1ee66aed94754ccf98e6c2008a41
  labels:
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
    app.kubernetes.io/name: model-registry-sync-operator
    app.kubernetes.io/managed-by: quarkus
  name: model-registry-sync-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 0.0.1-SNAPSHOT
      app.kubernetes.io/name: model-registry-sync-operator
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2023-05-24 - 17:02:35 +0000
        app.quarkus.io/commit-id: c5ccbf4787ad1ee66aed94754ccf98e6c2008a41
      labels:
        app.kubernetes.io/version: 0.0.1-SNAPSHOT
        app.kubernetes.io/name: model-registry-sync-operator
        app.kubernetes.io/managed-by: quarkus
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: docker.io/andreatp/model-registry-sync-operator:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: model-registry-sync-operator
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 8443
              name: https
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/started
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
      serviceAccountName: model-registry-sync-operator
